package signers

import documentation "github.com/FacileStudio/Plume/apps/api/internal/documentation"

var Documentation = documentation.Module{
	Name:        "signers",
	Description: "Manage document signers and signing flow.",
	Routes: []documentation.Route{
		{
			Method:       "GET",
			Path:         "/documents/{docId}/signers",
			Summary:      "List signers for a document",
			Auth:         "bearer",
			ResponseBody: "[]SignerResponse",
			PathParams:   []documentation.Field{{Name: "docId", Type: "int", Description: "Document ID"}},
		},
		{
			Method:       "POST",
			Path:         "/documents/{docId}/signers",
			Summary:      "Add a signer to a document",
			Auth:         "bearer",
			RequestBody:  "AddSignerRequest",
			ResponseBody: "SignerResponse",
			PathParams:   []documentation.Field{{Name: "docId", Type: "int", Description: "Document ID"}},
		},
		{
			Method:     "DELETE",
			Path:       "/signers/{id}",
			Summary:    "Remove a signer",
			Auth:       "bearer",
			PathParams: []documentation.Field{{Name: "id", Type: "int", Description: "Signer ID"}},
		},
		{
			Method:       "POST",
			Path:         "/signers/{id}/remind",
			Summary:      "Resend the signing invitation",
			Description:  "Owner-only. Re-sends the signing invitation email to a pending signer. Rate limited to one call per minute per signer.",
			Auth:         "bearer",
			ResponseBody: "RemindResponse",
			PathParams:   []documentation.Field{{Name: "id", Type: "int", Description: "Signer ID"}},
		},
		{
			Method:       "GET",
			Path:         "/sign/{token}",
			Summary:      "Get signing view",
			Description:  "Public endpoint. Returns the document, signer info, and fields for signing.",
			Auth:         "",
			ResponseBody: "SigningView",
			PathParams:   []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
		{
			Method:       "GET",
			Path:         "/sign/{token}/status",
			Summary:      "Get signing progress",
			Description:  "Public endpoint. Returns the participant roster and overall document status (works in any non-draft state) to power the post-signing audit view.",
			Auth:         "",
			ResponseBody: "SigningStatusResponse",
			PathParams:   []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
		{
			Method:      "POST",
			Path:        "/sign/{token}",
			Summary:     "Submit signature",
			Description: "Public endpoint. Submits field values and records the signature. Rejected with invalid_argument if any field the sender marked required for this signer is left empty (a checkbox must be ticked; every other type must be non-blank).",
			Auth:        "",
			RequestBody: "SubmitSignatureRequest",
			PathParams:  []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
		{
			Method:      "GET",
			Path:        "/sign/{token}/file",
			Summary:     "Download the document being signed",
			Description: "Public endpoint. Streams the PDF for the signing view as application/pdf rather than JSON.",
			Auth:        "",
			PathParams:  []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
		{
			Method:      "GET",
			Path:        "/sign/{token}/opened.gif",
			Summary:     "Signing invitation tracking pixel",
			Description: "Public endpoint. Returns a 1x1 GIF and records that the signer opened the invitation email.",
			Auth:        "",
			PathParams:  []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
		{
			Method:      "POST",
			Path:        "/sign/{token}/decline",
			Summary:     "Decline to sign",
			Description: "Public endpoint. Marks the signer as declined and moves the document to declined. Takes no body.",
			Auth:        "",
			PathParams:  []documentation.Field{{Name: "token", Type: "string", Description: "Signer token"}},
		},
	},
}
